"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type GeneratedExercise = {
  exercise_name: string;
  exercise_id: string | null;
  sets: number;
  reps: number;
  notes: string | null;
};

type GeneratedWorkout = {
  name: string;
  exercises: GeneratedExercise[];
};

export default function AiWorkoutPage() {
  const router = useRouter();
  const [goal, setGoal] = useState("");
  const [equipment, setEquipment] = useState("");
  const [duration, setDuration] = useState("45");
  const [difficulty, setDifficulty] = useState("intermediate");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [workout, setWorkout] = useState<GeneratedWorkout | null>(null);

  async function onGenerate(event: FormEvent) {
    event.preventDefault();
    setError(null);
    setWorkout(null);
    setIsGenerating(true);
    try {
      const response = await fetch("/api/ai/generate-workout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          goal,
          equipment: equipment || null,
          duration_minutes: Number(duration),
          difficulty,
        }),
      });
      const body = await response.json();
      if (!response.ok) {
        setError(body?.error?.message ?? "Couldn't generate a workout. Please try again.");
        return;
      }
      setWorkout(body.data);
    } finally {
      setIsGenerating(false);
    }
  }

  async function onSave() {
    if (!workout) return;
    setIsSaving(true);
    setError(null);
    const savableExercises = workout.exercises.filter((e) => e.exercise_id);
    try {
      const response = await fetch("/api/workouts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: workout.name,
          performed_at: new Date().toISOString().slice(0, 10),
          notes: "Generated by AI Coach",
          exercises: savableExercises.map((e) => ({
            exercise_id: e.exercise_id,
            sets: e.sets,
            reps: e.reps,
            notes: e.notes,
          })),
        }),
      });
      const body = await response.json();
      if (!response.ok) {
        setError(body?.error?.message ?? "Couldn't save the workout. Please try again.");
        return;
      }
      router.push(`/workouts/${body.data.id}`);
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <div className="mx-auto flex max-w-2xl flex-col gap-6">
      <h1 className="text-2xl font-bold tracking-tight">Generate a workout</h1>

      <Card>
        <CardContent className="pt-6">
          <form onSubmit={onGenerate} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="goal">Goal</Label>
              <Input
                id="goal"
                placeholder="Build muscle, lose weight, general fitness…"
                value={goal}
                onChange={(e) => setGoal(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="equipment">Available equipment (optional)</Label>
              <Input
                id="equipment"
                placeholder="Barbell, dumbbells, bodyweight only…"
                value={equipment}
                onChange={(e) => setEquipment(e.target.value)}
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-2">
                <Label htmlFor="duration">Session length (minutes)</Label>
                <Input
                  id="duration"
                  type="number"
                  min={10}
                  max={180}
                  value={duration}
                  onChange={(e) => setDuration(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>Difficulty</Label>
                <Select value={difficulty} onValueChange={setDifficulty}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="beginner">Beginner</SelectItem>
                    <SelectItem value="intermediate">Intermediate</SelectItem>
                    <SelectItem value="advanced">Advanced</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            {error && <p className="text-sm font-medium text-destructive">{error}</p>}
            <Button type="submit" disabled={isGenerating}>
              {isGenerating ? "Generating…" : "Generate workout"}
            </Button>
          </form>
        </CardContent>
      </Card>

      {workout && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">{workout.name}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {workout.exercises.map((exercise, index) => (
              <div
                key={index}
                className="flex items-center justify-between rounded-md border border-border p-3 text-sm"
              >
                <div>
                  <p className="font-medium">{exercise.exercise_name}</p>
                  {!exercise.exercise_id && (
                    <p className="text-xs text-muted-foreground">
                      Not in our library — won&apos;t be saved
                    </p>
                  )}
                </div>
                <span className="text-muted-foreground">
                  {exercise.sets} x {exercise.reps}
                </span>
              </div>
            ))}
            <Button onClick={onSave} disabled={isSaving}>
              {isSaving ? "Saving…" : "Save as workout"}
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
